const personaDefaults = {
  admin: {
    id: 'bp-admin-default',
    name: 'Platform Overview',
    persona: 'admin',
    description: 'Admin start page with setup progress, user adoption, and credential health',
    licenseTier: 'essentials',
    isSystemDefault: true,
    widgets: [
      { id: 'admin-kpi-1', type: 'kpi-tile', colSpan: 4, position: 0, config: { variant: 'activeUsers' } },
      { id: 'admin-kpi-2', type: 'kpi-tile', colSpan: 4, position: 1, config: { variant: 'setupCompleteness' } },
      { id: 'admin-kpi-3', type: 'kpi-tile', colSpan: 4, position: 2, config: { variant: 'blueprintsAssigned' } },
      { id: 'admin-kpi-4', type: 'kpi-tile', colSpan: 4, position: 3, config: { variant: 'avgSessionDuration' } },
      { id: 'admin-setup', type: 'setup-checklist', colSpan: 8, position: 4, config: {} },
      { id: 'admin-creds', type: 'spend-breakdown', colSpan: 8, position: 5, config: { variant: 'credentialHealth' } },
      { id: 'admin-adoption', type: 'user-adoption', colSpan: 8, position: 6, config: {} },
      { id: 'admin-blueprints', type: 'spend-breakdown', colSpan: 8, position: 7, config: { variant: 'blueprintAssignments' } },
    ],
  },
  finops: {
    id: 'bp-finops-default',
    name: 'FinOps Command Center',
    persona: 'finops',
    description: 'Comprehensive view of spend, budgets, optimization, and anomalies',
    licenseTier: 'standard',
    isSystemDefault: true,
    widgets: [
      { id: 'finops-kpi-1', type: 'kpi-tile', colSpan: 4, position: 0, config: { variant: 'totalSpend' } },
      { id: 'finops-kpi-2', type: 'kpi-tile', colSpan: 4, position: 1, config: { variant: 'rightSizingSavings' } },
      { id: 'finops-kpi-3', type: 'kpi-tile', colSpan: 4, position: 2, config: { variant: 'commitmentCoverage' } },
      { id: 'finops-kpi-4', type: 'kpi-tile', colSpan: 4, position: 3, config: { variant: 'coinScore' } },
      { id: 'finops-spend', type: 'spend-trend', colSpan: 8, position: 4, config: {} },
      { id: 'finops-budget', type: 'budget-actuals', colSpan: 8, position: 5, config: {} },
      { id: 'finops-rightsizing', type: 'right-sizing', colSpan: 5, position: 6, config: {} },
      { id: 'finops-commitments', type: 'commitment-health', colSpan: 5, position: 7, config: {} },
      { id: 'finops-anomalies', type: 'anomaly-feed', colSpan: 6, position: 8, config: {} },
      { id: 'finops-allocation', type: 'spend-breakdown', colSpan: 16, position: 9, config: { variant: 'costAllocation' } },
    ],
  },
  devops: {
    id: 'bp-devops-default',
    name: 'Engineering Cost View',
    persona: 'devops',
    description: 'Team-scoped spend, right-sizing, anomalies, and governance',
    licenseTier: 'standard',
    isSystemDefault: true,
    widgets: [
      { id: 'devops-kpi-1', type: 'kpi-tile', colSpan: 4, position: 0, config: { variant: 'teamSpend' } },
      { id: 'devops-kpi-2', type: 'kpi-tile', colSpan: 4, position: 1, config: { variant: 'rightSizingSavingsTeam' } },
      { id: 'devops-kpi-3', type: 'kpi-tile', colSpan: 4, position: 2, config: { variant: 'activeAnomalies' } },
      { id: 'devops-kpi-4', type: 'kpi-tile', colSpan: 4, position: 3, config: { variant: 'tagCompliance' } },
      { id: 'devops-breakdown', type: 'spend-breakdown', colSpan: 8, position: 4, config: { variant: 'teamServices' } },
      { id: 'devops-forecast', type: 'forecast', colSpan: 8, position: 5, config: {} },
      { id: 'devops-rightsizing', type: 'right-sizing', colSpan: 5, position: 6, config: { variant: 'team' } },
      { id: 'devops-anomalies', type: 'anomaly-feed', colSpan: 5, position: 7, config: { variant: 'team' } },
      { id: 'devops-governance', type: 'governance-compliance', colSpan: 6, position: 8, config: {} },
      { id: 'devops-idle', type: 'idle-resources', colSpan: 16, position: 9, config: {} },
    ],
  },
  finance: {
    id: 'bp-finance-default',
    name: 'Executive Summary',
    persona: 'finance',
    description: 'High-level spend, budgets, forecasts, and commitment portfolio',
    licenseTier: 'essentials',
    isSystemDefault: true,
    widgets: [
      { id: 'finance-kpi-1', type: 'kpi-tile', colSpan: 4, position: 0, config: { variant: 'totalSpend' } },
      { id: 'finance-kpi-2', type: 'kpi-tile', colSpan: 4, position: 1, config: { variant: 'ytdSpend' } },
      { id: 'finance-kpi-3', type: 'kpi-tile', colSpan: 4, position: 2, config: { variant: 'commitmentSavings' } },
      { id: 'finance-kpi-4', type: 'kpi-tile', colSpan: 4, position: 3, config: { variant: 'spendGrowth' } },
      { id: 'finance-trend', type: 'spend-trend', colSpan: 8, position: 4, config: { variant: 'annual' } },
      { id: 'finance-bu', type: 'cost-by-business-unit', colSpan: 8, position: 5, config: {} },
      { id: 'finance-budget', type: 'budget-actuals', colSpan: 5, position: 6, config: { variant: 'quarterly' } },
      { id: 'finance-providers', type: 'provider-mix', colSpan: 5, position: 7, config: {} },
      { id: 'finance-commitments', type: 'commitment-health', colSpan: 6, position: 8, config: { variant: 'portfolio' } },
      { id: 'finance-mom', type: 'spend-breakdown', colSpan: 16, position: 9, config: { variant: 'monthOverMonth' } },
    ],
  },
};

export default personaDefaults;
