import {
  KpiTile,
  SpendTrend,
  SpendBreakdown,
  BudgetActuals,
  RightSizing,
  CommitmentHealth,
  AnomalyFeed,
  Forecast,
  CostByBusinessUnit,
  IdleResources,
  GovernanceCompliance,
  CoinScore,
  ProviderMix,
  SetupChecklist,
  UserAdoption,
} from '../components/widgets';

const widgetRegistry = {
  'kpi-tile': {
    name: 'KPI Tile',
    icon: 'Dashboard',
    category: 'KPIs',
    defaultColSpan: 4,
    allowedColSpans: [4, 8],
    tier: 'essentials',
    description: 'Single headline metric with trend indicator',
    component: KpiTile,
  },
  'spend-trend': {
    name: 'Spend Trend',
    icon: 'ChartLineData',
    category: 'Spend & Cost',
    defaultColSpan: 8,
    allowedColSpans: [8, 16],
    tier: 'essentials',
    description: 'Time-series spend view with forecast and budget overlay',
    component: SpendTrend,
  },
  'spend-breakdown': {
    name: 'Spend Breakdown',
    icon: 'ChartBar',
    category: 'Spend & Cost',
    defaultColSpan: 8,
    allowedColSpans: [8, 16],
    tier: 'essentials',
    description: 'Categorical breakdown of spend by dimension',
    component: SpendBreakdown,
  },
  'budget-actuals': {
    name: 'Budget vs. Actuals',
    icon: 'Finance',
    category: 'Budgets & Forecasting',
    defaultColSpan: 8,
    allowedColSpans: [8, 16],
    tier: 'essentials',
    description: 'Budget tracking with actual spend and forecast overlay',
    component: BudgetActuals,
  },
  'right-sizing': {
    name: 'Right-Sizing Opportunities',
    icon: 'Tuning',
    category: 'Optimization',
    defaultColSpan: 5,
    allowedColSpans: [5, 8, 16],
    tier: 'standard',
    description: 'Actionable right-sizing recommendations with savings potential',
    component: RightSizing,
  },
  'commitment-health': {
    name: 'Commitment Health',
    icon: 'Money',
    category: 'Optimization',
    defaultColSpan: 5,
    allowedColSpans: [5, 8],
    tier: 'standard',
    description: 'RI/Savings Plan utilization, coverage, and recommendations',
    component: CommitmentHealth,
  },
  'anomaly-feed': {
    name: 'Anomaly Feed',
    icon: 'WarningAlt',
    category: 'Monitoring',
    defaultColSpan: 6,
    allowedColSpans: [6, 8, 16],
    tier: 'essentials',
    description: 'Real-time list of cost anomalies requiring investigation',
    component: AnomalyFeed,
  },
  'forecast': {
    name: 'Forecast',
    icon: 'Growth',
    category: 'Budgets & Forecasting',
    defaultColSpan: 8,
    allowedColSpans: [8, 16],
    tier: 'essentials',
    description: 'Spend forecast with confidence intervals',
    component: Forecast,
  },
  'cost-by-business-unit': {
    name: 'Cost by Business Unit',
    icon: 'TreeViewAlt',
    category: 'Spend & Cost',
    defaultColSpan: 8,
    allowedColSpans: [8, 16],
    tier: 'essentials',
    description: 'Spend distribution across business units',
    component: CostByBusinessUnit,
  },
  'idle-resources': {
    name: 'Idle Resources',
    icon: 'PowerOff',
    category: 'Optimization',
    defaultColSpan: 16,
    allowedColSpans: [8, 16],
    tier: 'standard',
    description: 'Resources with zero or near-zero utilization',
    component: IdleResources,
  },
  'governance-compliance': {
    name: 'Governance & Compliance',
    icon: 'Policy',
    category: 'Monitoring',
    defaultColSpan: 6,
    allowedColSpans: [6, 8, 16],
    tier: 'standard',
    description: 'Tag compliance and policy violation status',
    component: GovernanceCompliance,
  },
  'coin-score': {
    name: 'COIN Score',
    icon: 'Meter',
    category: 'KPIs',
    defaultColSpan: 4,
    allowedColSpans: [4, 8],
    tier: 'premium',
    description: 'Cost Optimization Index -- overall optimization health score',
    component: CoinScore,
  },
  'provider-mix': {
    name: 'Provider Mix',
    icon: 'CloudServices',
    category: 'Spend & Cost',
    defaultColSpan: 5,
    allowedColSpans: [5, 8],
    tier: 'essentials',
    description: 'Spend distribution by cloud provider',
    component: ProviderMix,
  },
  'setup-checklist': {
    name: 'Setup Checklist',
    icon: 'TaskComplete',
    category: 'Admin',
    defaultColSpan: 8,
    allowedColSpans: [8, 16],
    tier: 'essentials',
    description: 'Onboarding progress for platform configuration',
    component: SetupChecklist,
  },
  'user-adoption': {
    name: 'User Adoption',
    icon: 'UserMultiple',
    category: 'Admin',
    defaultColSpan: 8,
    allowedColSpans: [8, 16],
    tier: 'essentials',
    description: 'User login and engagement trends',
    component: UserAdoption,
  },
};

export function getWidgetComponent(type) {
  return widgetRegistry[type]?.component || null;
}

export default widgetRegistry;
